version: "3.8"

services:
  test_ros2:
    container_name: cpp_ros2
    image: alejoxbg/test_ros2
    build: .

  python_ros2:
    container_name: py_ros2
    image: alejoxbg/test_ros2
    command: ros2 launch cpp_pkg test.launch.py